---
galaxy_info:
  author: Gustavo Giudici
  description: 
  company: Bastly http://bastly.com
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - development

dependencies:
  # - role: bastly.common-build
